# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(759, 505)
        font = QtGui.QFont()
        font.setFamily("Arial")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color:rgb(255, 250, 250);\n"
"font-family: Arial")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.block_2 = QtWidgets.QSplitter(self.centralwidget)
        self.block_2.setGeometry(QtCore.QRect(380, 30, 341, 161))
        self.block_2.setOrientation(QtCore.Qt.Horizontal)
        self.block_2.setObjectName("block_2")
        self.layoutWidget = QtWidgets.QWidget(self.block_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.customer_lb = QtWidgets.QLabel(self.layoutWidget)
        self.customer_lb.setObjectName("customer_lb")
        self.verticalLayout_4.addWidget(self.customer_lb)
        self.ty_opo_lb = QtWidgets.QLabel(self.layoutWidget)
        self.ty_opo_lb.setObjectName("ty_opo_lb")
        self.verticalLayout_4.addWidget(self.ty_opo_lb)
        self.fio_welder_lb = QtWidgets.QLabel(self.layoutWidget)
        self.fio_welder_lb.setObjectName("fio_welder_lb")
        self.verticalLayout_4.addWidget(self.fio_welder_lb)
        self.stigma_lb = QtWidgets.QLabel(self.layoutWidget)
        self.stigma_lb.setObjectName("stigma_lb")
        self.verticalLayout_4.addWidget(self.stigma_lb)
        self.layoutWidget1 = QtWidgets.QWidget(self.block_2)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.customer = QtWidgets.QLineEdit(self.layoutWidget1)
        self.customer.setObjectName("customer")
        self.verticalLayout_3.addWidget(self.customer)
        self.ty_opo = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ty_opo.setObjectName("ty_opo")
        self.verticalLayout_3.addWidget(self.ty_opo)
        self.fio_welder = QtWidgets.QLineEdit(self.layoutWidget1)
        self.fio_welder.setObjectName("fio_welder")
        self.verticalLayout_3.addWidget(self.fio_welder)
        self.stigma = QtWidgets.QLineEdit(self.layoutWidget1)
        self.stigma.setObjectName("stigma")
        self.verticalLayout_3.addWidget(self.stigma)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(40, 240, 321, 231))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.block_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.block_3.setContentsMargins(0, 0, 0, 0)
        self.block_3.setObjectName("block_3")
        self.vt_button = QtWidgets.QRadioButton(self.layoutWidget2)
        self.vt_button.setObjectName("vt_button")
        self.block_3.addWidget(self.vt_button)
        self.rt_button = QtWidgets.QRadioButton(self.layoutWidget2)
        self.rt_button.setObjectName("rt_button")
        self.block_3.addWidget(self.rt_button)
        self.ut_button = QtWidgets.QRadioButton(self.layoutWidget2)
        self.ut_button.setObjectName("ut_button")
        self.block_3.addWidget(self.ut_button)
        self.pt_button = QtWidgets.QRadioButton(self.layoutWidget2)
        self.pt_button.setObjectName("pt_button")
        self.block_3.addWidget(self.pt_button)
        self.mt_button = QtWidgets.QRadioButton(self.layoutWidget2)
        self.mt_button.setObjectName("mt_button")
        self.block_3.addWidget(self.mt_button)
        self.block_1 = QtWidgets.QSplitter(self.centralwidget)
        self.block_1.setGeometry(QtCore.QRect(20, 30, 331, 161))
        self.block_1.setStyleSheet("")
        self.block_1.setOrientation(QtCore.Qt.Horizontal)
        self.block_1.setObjectName("block_1")
        self.frame = QtWidgets.QFrame(self.block_1)
        self.frame.setStyleSheet("")
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.number_prot_lb = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.number_prot_lb.setFont(font)
        self.number_prot_lb.setStyleSheet("")
        self.number_prot_lb.setObjectName("number_prot_lb")
        self.verticalLayout_2.addWidget(self.number_prot_lb)
        self.num_programm_lb = QtWidgets.QLabel(self.frame)
        self.num_programm_lb.setObjectName("num_programm_lb")
        self.verticalLayout_2.addWidget(self.num_programm_lb)
        self.date_welding_lb = QtWidgets.QLabel(self.frame)
        self.date_welding_lb.setObjectName("date_welding_lb")
        self.verticalLayout_2.addWidget(self.date_welding_lb)
        self.date_control_lb = QtWidgets.QLabel(self.frame)
        self.date_control_lb.setObjectName("date_control_lb")
        self.verticalLayout_2.addWidget(self.date_control_lb)
        self.frame1 = QtWidgets.QFrame(self.block_1)
        self.frame1.setStyleSheet("")
        self.frame1.setObjectName("frame1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.number_prot = QtWidgets.QLineEdit(self.frame1)
        self.number_prot.setObjectName("number_prot")
        self.verticalLayout.addWidget(self.number_prot)
        self.num_programm = QtWidgets.QLineEdit(self.frame1)
        self.num_programm.setObjectName("num_programm")
        self.verticalLayout.addWidget(self.num_programm)
        self.date_welding = QtWidgets.QLineEdit(self.frame1)
        self.date_welding.setObjectName("date_welding")
        self.verticalLayout.addWidget(self.date_welding)
        self.date_control = QtWidgets.QLineEdit(self.frame1)
        self.date_control.setObjectName("date_control")
        self.verticalLayout.addWidget(self.date_control)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(420, 240, 281, 231))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.add_doc = QtWidgets.QPushButton(self.layoutWidget3)
        self.add_doc.setStyleSheet("QPushButton {\n"
"color:black;\n"
"background-color:rgba(220, 220, 220, 30);\n"
"border: 1px solid rgb(0, 0, 0);\n"
"border-radius: 7px;\n"
"\n"
"}\n"
"")
        self.add_doc.setObjectName("add_doc")
        self.verticalLayout_5.addWidget(self.add_doc)
        self.add_metodology = QtWidgets.QPushButton(self.layoutWidget3)
        self.add_metodology.setStyleSheet("QPushButton {\n"
"color:black;\n"
"background-color:rgba(220, 220, 220, 30);\n"
"border: 1px solid rgb(0, 0, 0);\n"
"border-radius: 7px;\n"
"\n"
"}\n"
"")
        self.add_metodology.setObjectName("add_metodology")
        self.verticalLayout_5.addWidget(self.add_metodology)
        self.add_kss = QtWidgets.QPushButton(self.layoutWidget3)
        self.add_kss.setStyleSheet("QPushButton {\n"
"color:black;\n"
"background-color:rgba(220, 220, 220, 30);\n"
"border: 1px solid rgb(0, 0, 0);\n"
"border-radius: 7px;\n"
"}")
        self.add_kss.setObjectName("add_kss")
        self.verticalLayout_5.addWidget(self.add_kss)
        self.create = QtWidgets.QPushButton(self.layoutWidget3)
        self.create.setStyleSheet("QPushButton {\n"
"color:black;\n"
"background-color:rgba(220, 220, 220, 30);\n"
"border: 1px solid rgb(0, 0, 0);\n"
"border-radius: 7px;\n"
"\n"
"}\n"
"")
        self.create.setObjectName("create")
        self.verticalLayout_5.addWidget(self.create)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Reports"))
        self.customer_lb.setText(_translate("MainWindow", "Заказчик"))
        self.ty_opo_lb.setText(_translate("MainWindow", "ТУ ОПО"))
        self.fio_welder_lb.setText(_translate("MainWindow", "ФИО сварщика"))
        self.stigma_lb.setText(_translate("MainWindow", "Клеймо сварщика"))
        self.vt_button.setText(_translate("MainWindow", "Визуальный и измерительный (ВИК)"))
        self.rt_button.setText(_translate("MainWindow", "Радиографический (РК)"))
        self.ut_button.setText(_translate("MainWindow", "Ультразвуковой (УК)"))
        self.pt_button.setText(_translate("MainWindow", "Капиллярный (ПВК)"))
        self.mt_button.setText(_translate("MainWindow", "Магнитопорошковый (МПК)"))
        self.number_prot_lb.setText(_translate("MainWindow", "№ Протокола"))
        self.num_programm_lb.setText(_translate("MainWindow", "№ Программы"))
        self.date_welding_lb.setText(_translate("MainWindow", "Дата сварки"))
        self.date_control_lb.setText(_translate("MainWindow", "Дата контроля"))
        self.add_doc.setText(_translate("MainWindow", "Добавить докумен"))
        self.add_metodology.setText(_translate("MainWindow", "Добавить методику"))
        self.add_kss.setText(_translate("MainWindow", "Добавить КСС"))
        self.create.setText(_translate("MainWindow", "Создать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
