# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_metodology_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_metodology(object):
    def setupUi(self, new_metodology):
        new_metodology.setObjectName("new_metodology")
        new_metodology.resize(371, 173)
        new_metodology.setStyleSheet("background-color:rgb(255, 250, 250);\n"
"font-family: Arial")
        self.add_metodology = QtWidgets.QPushButton(new_metodology)
        self.add_metodology.setGeometry(QtCore.QRect(90, 140, 191, 16))
        self.add_metodology.setStyleSheet("QPushButton {\n"
"color:black;\n"
"background-color:rgba(220, 220, 220, 30);\n"
"border: 1px solid rgb(0, 0, 0);\n"
"border-radius: 7px;\n"
"}")
        self.add_metodology.setObjectName("add_metodology")
        self.layoutWidget = QtWidgets.QWidget(new_metodology)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 20, 251, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.methodology_lb = QtWidgets.QLabel(self.layoutWidget)
        self.methodology_lb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.methodology_lb.setScaledContents(False)
        self.methodology_lb.setWordWrap(False)
        self.methodology_lb.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.methodology_lb.setObjectName("methodology_lb")
        self.verticalLayout.addWidget(self.methodology_lb)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)

        self.retranslateUi(new_metodology)
        QtCore.QMetaObject.connectSlotsByName(new_metodology)

    def retranslateUi(self, new_metodology):
        _translate = QtCore.QCoreApplication.translate
        new_metodology.setWindowTitle(_translate("new_metodology", "Dialog"))
        self.add_metodology.setText(_translate("new_metodology", "Сохранить"))
        self.methodology_lb.setText(_translate("new_metodology", "                      Методика контроля"))
        self.comboBox.setItemText(0, _translate("new_metodology", "ГОСТ 7512-82"))
        self.comboBox.setItemText(1, _translate("new_metodology", "ГОСТ Р 55724"))
        self.comboBox.setItemText(2, _translate("new_metodology", "ГОСТ 18442-80"))
        self.comboBox.setItemText(3, _translate("new_metodology", "ГОСТ 21105-87"))
        self.comboBox.setItemText(4, _translate("new_metodology", "СТО Газпром 2-2.4-083-2006"))
        self.comboBox.setItemText(5, _translate("new_metodology", "СТО 9701105632-003-2021"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    new_metodology = QtWidgets.QDialog()
    ui = Ui_new_metodology()
    ui.setupUi(new_metodology)
    new_metodology.show()
    sys.exit(app.exec_())
