# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_kss_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_kss(object):
    def setupUi(self, new_kss):
        new_kss.setObjectName("new_kss")
        new_kss.resize(363, 333)
        new_kss.setStyleSheet("background-color:rgb(255, 250, 250);\n"
"font-family: Arial")
        self.add_kss = QtWidgets.QPushButton(new_kss)
        self.add_kss.setGeometry(QtCore.QRect(90, 300, 191, 16))
        self.add_kss.setStyleSheet("QPushButton {\n"
"color:black;\n"
"background-color:rgba(220, 220, 220, 30);\n"
"border: 1px solid rgb(0, 0, 0);\n"
"border-radius: 7px;\n"
"}")
        self.add_kss.setObjectName("add_kss")
        self.splitter = QtWidgets.QSplitter(new_kss)
        self.splitter.setGeometry(QtCore.QRect(21, 22, 141, 241))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.kss_lb = QtWidgets.QLabel(self.splitter)
        self.kss_lb.setObjectName("kss_lb")
        self.lb_diameter = QtWidgets.QLabel(self.splitter)
        self.lb_diameter.setObjectName("lb_diameter")
        self.lb_thickness = QtWidgets.QLabel(self.splitter)
        self.lb_thickness.setObjectName("lb_thickness")
        self.standard_size_lb = QtWidgets.QLabel(self.splitter)
        self.standard_size_lb.setObjectName("standard_size_lb")
        self.steel_grade_lb = QtWidgets.QLabel(self.splitter)
        self.steel_grade_lb.setObjectName("steel_grade_lb")
        self.welding_metod_lb = QtWidgets.QLabel(self.splitter)
        self.welding_metod_lb.setObjectName("welding_metod_lb")
        self.layoutWidget = QtWidgets.QWidget(new_kss)
        self.layoutWidget.setGeometry(QtCore.QRect(180, 15, 171, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.kss = QtWidgets.QLineEdit(self.layoutWidget)
        self.kss.setObjectName("kss")
        self.verticalLayout.addWidget(self.kss)
        self.diameter = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.diameter.setObjectName("diameter")
        self.diameter.setMaximum(1500)
        self.verticalLayout.addWidget(self.diameter)
        self.thickness = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.thickness.setObjectName("thickness")
        self.thickness.setMaximum(50)
        self.verticalLayout.addWidget(self.thickness)
        self.standard_size = QtWidgets.QLineEdit(self.layoutWidget)
        self.standard_size.setObjectName("standard_size")
        self.verticalLayout.addWidget(self.standard_size)
        self.steel_grade = QtWidgets.QComboBox(self.layoutWidget)
        self.steel_grade.setObjectName("steel_grade")
        self.steel_grade.addItem("")
        self.steel_grade.addItem("")
        self.steel_grade.addItem("")
        self.steel_grade.addItem("")
        self.steel_grade.addItem("")
        self.steel_grade.addItem("")
        self.steel_grade.addItem("")
        self.steel_grade.addItem("")
        self.steel_grade.addItem("")
        self.steel_grade.addItem("")
        self.verticalLayout.addWidget(self.steel_grade)
        self.welding_metod = QtWidgets.QComboBox(self.layoutWidget)
        self.welding_metod.setObjectName("welding_metod")
        self.welding_metod.addItem("")
        self.welding_metod.addItem("")
        self.welding_metod.addItem("")
        self.welding_metod.addItem("")
        self.welding_metod.addItem("")
        self.welding_metod.addItem("")
        self.welding_metod.addItem("")
        self.welding_metod.addItem("")
        self.welding_metod.addItem("")
        self.welding_metod.addItem("")
        self.welding_metod.addItem("")
        self.verticalLayout.addWidget(self.welding_metod)

        self.retranslateUi(new_kss)
        QtCore.QMetaObject.connectSlotsByName(new_kss)

    def retranslateUi(self, new_kss):
        _translate = QtCore.QCoreApplication.translate
        new_kss.setWindowTitle(_translate("new_kss", "Dialog"))
        self.add_kss.setText(_translate("new_kss", "Сохранить"))
        self.kss_lb.setText(_translate("new_kss", "Идентификатор/КCC"))
        self.lb_diameter.setText(_translate("new_kss", "Диаметр:"))
        self.lb_thickness.setText(_translate("new_kss", "Толщна (min)"))
        self.standard_size_lb.setText(_translate("new_kss", "Типоразмер "))
        self.steel_grade_lb.setText(_translate("new_kss", "Марка стали"))
        self.welding_metod_lb.setText(_translate("new_kss", "Способ сварки"))
        self.steel_grade.setItemText(0, _translate("new_kss", "09Г2С"))
        self.steel_grade.setItemText(1, _translate("new_kss", "10Г2ФБЮ"))
        self.steel_grade.setItemText(2, _translate("new_kss", "12Х18Н10Т"))
        self.steel_grade.setItemText(3, _translate("new_kss", "08Х18Н10"))
        self.steel_grade.setItemText(4, _translate("new_kss", "TP321"))
        self.steel_grade.setItemText(5, _translate("new_kss", "К52"))
        self.steel_grade.setItemText(6, _translate("new_kss", "К60"))
        self.steel_grade.setItemText(7, _translate("new_kss", "ст.3"))
        self.steel_grade.setItemText(8, _translate("new_kss", "ст.20"))
        self.steel_grade.setItemText(9, _translate("new_kss", "сталь"))
        self.welding_metod.setItemText(0, _translate("new_kss", "РД"))
        self.welding_metod.setItemText(1, _translate("new_kss", "РДВ"))
        self.welding_metod.setItemText(2, _translate("new_kss", "РАД"))
        self.welding_metod.setItemText(3, _translate("new_kss", "МАДП"))
        self.welding_metod.setItemText(4, _translate("new_kss", "МП"))
        self.welding_metod.setItemText(5, _translate("new_kss", "ААД"))
        self.welding_metod.setItemText(6, _translate("new_kss", "АПГ"))
        self.welding_metod.setItemText(7, _translate("new_kss", "ААДП"))
        self.welding_metod.setItemText(8, _translate("new_kss", "АФ"))
        self.welding_metod.setItemText(9, _translate("new_kss", "МПС"))
        self.welding_metod.setItemText(10, _translate("new_kss", "МПГ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    new_kss = QtWidgets.QDialog()
    ui = Ui_new_kss()
    ui.setupUi(new_kss)
    new_kss.show()
    sys.exit(app.exec_())
